name: Build LaTeX Document
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  # Uses Ubuntu runner
    
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Compile LaTeX document
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex  # Your main LaTeX file
          compiler: latexmk    # Default compiler
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          latexmk_use_xelatex: true  # Use XeLaTeX instead of pdfLaTeX
          pre_compile: |
            tlmgr update --self
            tlmgr install moderncv
            tlmgr install fontawesome
          post_compile: |
            latexmk -c  # Clean up temporary files
            
      # Upload PDF as artifact
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: main.pdf  # Path to generated PDF
          retention-days: 5  # Keep artifact for 5 days