name: Build and Release Resume
on:
  push:
    branches: [master]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            latexmk
            xcolor
            fontspec
            geometry
            enumitem
            hyperref
            marvosym
            fontawesome
            ifthen
            etoolbox
            fancyhdr
            microtype

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y qpdf chktex r-base

      - name: Build LaTeX document using custom latexmkrc
        run: |
          latexmk -r ./latexmkrc -pdf -halt-on-error main.tex

      - name: Rename PDF
        run: mv main.pdf "Yuvraj Raghuvanshi.pdf"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Yuvraj Raghuvanshi Resume (${{ env.DATE }})"
          tag_name: resume-${{ env.DATE }}
          body: "Professional Resume - Yuvraj Raghuvanshi"
          files: Yuvraj Raghuvanshi.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
