name: Build and Release Resume
on:
  push:
    branches: [master]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          pre_compile: |
            tlmgr update --self
            tlmgr install moderncv
            tlmgr install fontawesome

      - name: Rename PDF
        run: mv main.pdf "Yuvraj Raghuvanshi.pdf"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Yuvraj Raghuvanshi Resume (${{ env.DATE }})"
          tag_name: resume-${{ env.DATE }}
          body: "Professional Resume - Yuvraj Raghuvanshi"
          files: Yuvraj Raghuvanshi.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
